
build:
  version: "1.0"

accounts:
  message: "Welcome to DummyBank cards related local APIs "
  contactDetails:
    name: "Rohan Rana - Developer"
    email: "rohan@dev.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
